version: "3"
services:
  #Graphql API
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # https://stackoverflow.com/a/32785014
    depends_on:
      - mongo-db
    ports:
      - '8080:8080'
      - '9229:9229'
    tty: true

  # MongoDB container
  mongo-db:
    image: mongo:4.2-bionic
    environment:
      - MONGO_INITDB_DATABASE=mongo-db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo-db

volumes:
  mongo-data:
